//! Core NFT listing function — orchestrates the full marketplace listing flow.
//!
//! Acceptance criteria:
//! 1. Validate listing (price, payment asset, expiration, no duplicate active listing)
//! 2. Verify ownership (caller must own the NFT)
//! 3. Generate listing ID (monotonic counter)
//! 4. Store listing (persistent storage)
//! 5. Emit listing event (NftListedEvent for off-chain indexers)
//! 6. Return listing ID

use soroban_sdk::Env;

use crate::listing_id_generator;
use crate::listing_request::ListingRequest;
use crate::types::{Error, ListingId};

use super::listing_storage as marketplace_listing_storage;
use super::listing_validator;
use super::types::{Listing, ListingStatus};

/// List an NFT for sale in the marketplace.
///
/// This is the single entry point for creating a marketplace listing. It
/// performs all pre-condition checks, generates a unique listing ID, persists
/// the listing, and emits an event so off-chain indexers can track active
/// listings.
///
/// # Flow
///
/// ```text
/// 1. Validate listing invariants (via listing_validator::validate_listing)
/// 2. Generate unique listing ID (via listing_id_generator)
/// 3. Construct full Listing record
/// 4. Persist to storage (via marketplace_listing_storage)
/// 5. Emit NftListedEvent (via nft_listed_event)
/// 6. Return the listing ID
/// ```
///
/// # Arguments
/// * `env`     — Contract environment.
/// * `request` — The listing request from the seller (token_id, price, asset, expiration).
///
/// # Returns
/// The unique [`ListingId`] assigned to this listing.
///
/// # Errors
/// | Error | Condition |
/// |-------|-----------|
/// | `ContractPaused` | Contract is paused. |
/// | `TokenNotFound` | NFT does not exist. |
/// | `Unauthorized` | Caller is not the token owner. |
/// | `InvalidSalePrice` | Price is zero or negative. |
/// | `PriceOverflow` | Price exceeds maximum allowed. |
/// | `UnsupportedAsset` | Payment asset is not supported. |
/// | `DuplicateRecord` | An active listing already exists for this token. |
/// | `InvalidConfig` | Expiration is in the past. |
/// | `InvalidLimit` | Listing ID counter overflowed. |
pub fn list_nft(env: &Env, request: &ListingRequest) -> Result<ListingId, Error> {
    // 1. Validate all listing invariants (pause guard, owner check, price, asset,
    //    duplicate, expiration).
    listing_validator::validate_listing(
        env,
        &request.seller,
        request.token_id,
        request.price,
        &request.payment_asset,
        request.expiration,
    )?;

    // 2. Generate a unique listing ID.
    let listing_id = listing_id_generator::generate_listing_id(env)?;

    // 3. Construct the full marketplace Listing record.
    let now = env.ledger().timestamp();
    let listing = Listing {
        token_id: request.token_id,
        seller: request.seller.clone(),
        price: request.price,
        payment_asset: request.payment_asset.clone(),
        expires_at: request.expiration,
        status: ListingStatus::Active,
        created_at: now,
        buyer: None,
        sold_at: None,
    };

    // 4. Persist the listing to storage.
    marketplace_listing_storage::save_listing(env, &listing);

    // 5. Emit the NftListedEvent for off-chain indexers.
    crate::nft_listed_event::emit_nft_listed(
        env,
        listing_id,
        request.token_id,
        &request.seller,
        request.price,
        &request.payment_asset,
        now,
    );

    // 6. Return the listing ID.
    Ok(listing_id)
}

/// Re-export the validator so callers can use it directly if needed.
pub use super::listing_validator::validate_listing;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::payment_currency;
    use crate::token_owner_storage;
    use crate::types::TokenId;
    use soroban_sdk::testutils::Address as _;
    use soroban_sdk::{Address, Env};

    /// Helper: mint an NFT by assigning ownership and adding a supported currency.
    fn setup(env: &Env, token_id: TokenId, owner: &Address, asset: &Address) {
        token_owner_storage::assign_owner(env, token_id, owner, token_id).unwrap();
        let _ = payment_currency::add_currency(env, asset.clone());
    }

    /// Build a ListingRequest for testing.
    fn make_request(
        env: &Env,
        token_id: TokenId,
        seller: &Address,
        price: i128,
        asset: &Address,
        expiration: u64,
    ) -> ListingRequest {
        ListingRequest {
            listing_id: 0, // generated by list_nft
            token_id,
            price,
            payment_asset: asset.clone(),
            expiration,
            seller: seller.clone(),
        }
    }

    #[test]
    fn list_nft_returns_unique_listing_id() {
        let env = Env::default();
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        setup(&env, 1, &seller, &asset);

        let id1 = list_nft(&env, &make_request(&env, 1, &seller, 1_000, &asset, 0)).unwrap();
        assert_eq!(id1, 1);

        // Must remove and relist to get a new ID for the same token.
        crate::marketplace::listing_storage::remove_listing(&env, 1);

        let id2 = list_nft(&env, &make_request(&env, 1, &seller, 2_000, &asset, 0)).unwrap();
        assert_eq!(id2, 2);
    }

    #[test]
    fn list_nft_rejects_when_paused() {
        let env = Env::default();
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        setup(&env, 1, &seller, &asset);
        crate::pause_state::save_pause_state(&env, true);

        let result = list_nft(&env, &make_request(&env, 1, &seller, 1_000, &asset, 0));
        assert_eq!(result, Err(Error::ContractPaused));
    }

    #[test]
    fn list_nft_rejects_non_owner() {
        let env = Env::default();
        let owner = Address::generate(&env);
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        setup(&env, 1, &owner, &asset);

        let result = list_nft(&env, &make_request(&env, 1, &seller, 1_000, &asset, 0));
        assert_eq!(result, Err(Error::Unauthorized));
    }

    #[test]
    fn list_nft_rejects_zero_price() {
        let env = Env::default();
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        setup(&env, 1, &seller, &asset);

        let result = list_nft(&env, &make_request(&env, 1, &seller, 0, &asset, 0));
        assert_eq!(result, Err(Error::InvalidSalePrice));
    }

    #[test]
    fn list_nft_rejects_negative_price() {
        let env = Env::default();
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        setup(&env, 1, &seller, &asset);

        let result = list_nft(&env, &make_request(&env, 1, &seller, -100, &asset, 0));
        assert_eq!(result, Err(Error::InvalidSalePrice));
    }

    #[test]
    fn list_nft_rejects_price_overflow() {
        let env = Env::default();
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        setup(&env, 1, &seller, &asset);

        let result = list_nft(&env, &make_request(&env, 1, &seller, i128::MAX, &asset, 0));
        assert_eq!(result, Err(Error::PriceOverflow));
    }

    #[test]
    fn list_nft_rejects_unsupported_payment_asset() {
        let env = Env::default();
        let seller = Address::generate(&env);
        let unsupported = Address::generate(&env);

        setup(&env, 1, &seller, &Address::generate(&env)); // support a different asset

        let result = list_nft(&env, &make_request(&env, 1, &seller, 1_000, &unsupported, 0));
        assert_eq!(result, Err(Error::UnsupportedAsset));
    }

    #[test]
    fn list_nft_rejects_duplicate_active_listing() {
        let env = Env::default();
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        setup(&env, 1, &seller, &asset);

        let _ = list_nft(&env, &make_request(&env, 1, &seller, 1_000, &asset, 0));

        // Attempting to list the same token again should fail.
        let result = list_nft(&env, &make_request(&env, 1, &seller, 2_000, &asset, 0));
        assert_eq!(result, Err(Error::DuplicateRecord));
    }

    #[test]
    fn list_nft_rejects_past_expiration() {
        let env = Env::default();
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        setup(&env, 1, &seller, &asset);

        // expiration = 1 is in the past relative to default ledger timestamp.
        let result = list_nft(&env, &make_request(&env, 1, &seller, 1_000, &asset, 1));
        assert_eq!(result, Err(Error::InvalidConfig));
    }

    #[test]
    fn list_nft_stores_listing_with_correct_fields() {
        let env = Env::default();
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        setup(&env, 1, &seller, &asset);

        let listing_id =
            list_nft(&env, &make_request(&env, 1, &seller, 5_000, &asset, 0)).unwrap();
        assert_eq!(listing_id, 1);

        // Verify the listing was stored correctly via the marketplace storage.
        let stored = crate::marketplace::listing_storage::get_listing(&env, 1).unwrap();
        assert_eq!(stored.token_id, 1);
        assert_eq!(stored.seller, seller);
        assert_eq!(stored.price, 5_000);
        assert_eq!(stored.payment_asset, asset);
        assert_eq!(stored.status, ListingStatus::Active);
        assert_eq!(stored.buyer, None);
        assert_eq!(stored.sold_at, None);
    }

    #[test]
    fn list_nft_emits_nft_listed_event() {
        use soroban_sdk::testutils::Events;

        let env = Env::default();
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        setup(&env, 1, &seller, &asset);

        let _listing_id =
            list_nft(&env, &make_request(&env, 1, &seller, 3_000, &asset, 0)).unwrap();

        // Verify exactly one event was emitted (the NftListedEvent).
        let events = env.events().all();
        assert_eq!(events.events().len(), 1);
    }

    #[test]
    fn list_nft_allows_relisting_after_removal() {
        let env = Env::default();
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        setup(&env, 1, &seller, &asset);

        let id1 = list_nft(&env, &make_request(&env, 1, &seller, 1_000, &asset, 0)).unwrap();
        assert_eq!(id1, 1);

        // Cancel / remove the listing.
        crate::marketplace::listing_storage::remove_listing(&env, 1);

        // Relist the same token — should succeed with a new ID.
        let id2 = list_nft(&env, &make_request(&env, 1, &seller, 2_000, &asset, 0)).unwrap();
        assert_eq!(id2, 2);
    }

    #[test]
    fn list_nft_accepts_valid_future_expiration() {
        let env = Env::default();
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        setup(&env, 1, &seller, &asset);

        // Use a far-future expiration.
        let result = list_nft(&env, &make_request(&env, 1, &seller, 1_000, &asset, 1_700_000_000));
        assert!(result.is_ok());
    }

    #[test]
    fn list_nft_rejects_token_not_found() {
        let env = Env::default();
        let seller = Address::generate(&env);
        let asset = Address::generate(&env);

        // Do NOT set up token ownership.
        let _ = payment_currency::add_currency(&env, asset.clone());

        let result = list_nft(&env, &make_request(&env, 999, &seller, 1_000, &asset, 0));
        assert_eq!(result, Err(Error::TokenNotFound));
    }
}
